spring:
  application:
    name: entities-streamer
  kafka:
    consumer:
      group-id: student_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://schema-registry:8081

topic: streamable-entities
server:
  port : 8072