spring:
  application:
    name: raw-data-listener
  kafka:
    bootstrap-servers: broker:29092
    producer:
      properties:
        allow.auto.create.topics: false
        schema.registry.url: http://schema-registry:8081
      group-id: student_group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: student_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.reader: true

consume-from: raw-data-events
produce-to: streamable-entities
interface-name: some-ais
