spring:
  application:
    name: sensor-connector
  kafka:
    bootstrap-servers: broker:29092
    producer:
      properties:
        allow.auto.create.topics: true
        schema.registry.url: http://schema-registry:8081
      group-id: student_group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
kafka:
  produce:
    to:
      topic: nca-raw-data-events
interface-configuration:
    host: 153.44.253.27
    port: 5631