spring:
  application:
    name: raw-data-fetcher
  kafka:
    producer:
      properties:
        schema.registry.url: http://localhost:8081
        allow.auto.create.topics: false
      bootstrap-servers: localhost:9092
      group-id: student_group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
topic: new-raw-data-event